### ISSUE TITLE
[Github]organizationのPermissionについて

### ISSUE THREAD

**Issue by ysnkw21** [2017pro02/jinkawa-android#10]
organizationのpermissionがRead permissionになっているためにissueのcloseやassign，labelやmilestoneの適応，pull requestのmerge，closeなど諸々が行えない。

**Comment by taross** [comment]
なるほどね

**Comment by ysnkw21** [comment]
owner権限ある人に頼まないとだめかね？
それかチームのmaintainerならいけるかもと思ったけど，このRepositoryはJinkawaTeamのRepositoryになってないね

**Comment by ysnkw21** [comment]
permissionを変更してもらったのでcloseします
